### ISSUE TITLE
[CRC] Max size bound to max single DMA transfer

### ISSUE THREAD

**Issue by vrepetenko** [ChibiOS/ChibiOS-Contrib#161]
Hi,

there is a problem with CRC Driver (community) with CRC_USE_DMA=TRUE,
driver does not work correctly with buffer more 256k due to DMA limitation. 
ChibiOS version - 17.6.3

**Comment by fpoussin** [comment]
Seems like we need update the buffer pointer and restart a transfer in the DMA interrupt handler

https://github.com/ChibiOS/ChibiOS-Contrib/blob/ae7a4d40b84d8afc999691577210696f16e682f6/os/hal/ports/STM32/LLD/CRCv1/hal_crc_lld.c#L110
