### ISSUE TITLE
SDRAM start leads to panic (SV4)

### ISSUE THREAD

**Issue by elagil** [ChibiOS/ChibiOS-Contrib#210]
The current version of SDRAM drivers breaks execution when calling `sdramStart()` because of nested calls to `osalSysLock()`. After `sdram_lld_start() -> sdram_lld_init_sequence()`, the thread is put to sleep with `osalThreadSleepMilliseconds()`, which also contains a `osalSysLock()` statement, leading to the SV4 panic.

I suggest to remove the lock statements from `sdramStart()` to restore functionality. Are they actually required? If not, I can create a pull request.

**Comment by fpoussin** [comment]
Hi,

Thanks for finding this bug.
osalThreadSleepMilliseconds could be replaced by **osalSysPolledDelayX**.

The start/stop function locks are needed for driver state consistency.

**Comment by elagil** [comment]
Good to know, I now replaced the delay with and do some testing.

`osalSysPolledDelayX(TIME_US2I(100))`

**Comment by fpoussin** [comment]
Feel free to open a pull request once testing is done
