### ISSUE TITLE
ChibiOS 19.1.x and 20.3.x branches

### ISSUE THREAD

**Issue by pierstitus** [ChibiOS/ChibiOS-Contrib#213]
Add branches for ChibiOS 19.1.x and 20.3.x

The current master seems to work with 19.1.x, and the commit messages indicate that too, but it would be much clearer to with the proper branch name.

For 20.3.x some changes to the makefiles and config files must be made. Apart from that at least the USB_MSD driver seems to work.

**Comment by fpoussin** [comment]
Hello,

Current master is for 19.1.x already.
It will move to its own branch like previous ones, and master will be updated for 20.3.x
