### ISSUE TITLE
not NUC123SD4AN0 but NUC123

### ISSUE THREAD

**Issue by elfmimi** [ChibiOS/ChibiOS-Contrib#237]
It should be os/hal/ports/NUMICRO/NUC123/platform.mk
instead of  os/hal/ports/NUMICRO/NUC123SD4AN0/platform.mk .
and so on.

**Comment by alexclewontin** [comment]
I agree with this, with the caveat that in the linker scripts we should be more specific (i.e. a NUC123xD4xx0.ld for the 68k/20k model and a NUC123xC2xx1.ld for the 36k/12k model)

**Comment by fpoussin** [comment]
Feel free to open a pull request
