### ISSUE TITLE
[Feature Request] Support for Raspberry Pi Pico

### ISSUE THREAD

**Issue by ryanm101** [ChibiOS/ChibiOS-Contrib#254]
https://www.raspberrypi.org/blog/raspberry-pi-silicon-pico-now-on-sale/

Support here for this is a pre-req for QMK (https://github.com/qmk/qmk_firmware/issues/11649)

**Comment by stapelberg** [comment]
Just in case anyone finds this issue and not the other forum thread: support for the Raspberry Pi Pico seems to be added to ChibiOS itself (not ChibiOS-Contrib). See https://forum.chibios.org/viewtopic.php?f=3&t=5800

**Comment by robin-jones** [comment]
If someone can update the mirror maintenance script for stable_21.6.x, I believe this board is now supported... @fpoussin?

**Comment by GrzegorzZajac000** [comment]
Any news on support for rpi Pico?

**Comment by fpoussin** [comment]
https://github.com/ChibiOS/ChibiOS/tree/master/demos/RP/RT-RP2040-PICO
Closing this as it's in the work

**Comment by Corallus-Caninus** [comment]
is this still in the works or finished? I haven't seen activity on the linked repository.
