### ISSUE TITLE
Roadmap for ChibiOS-Contrib 21.11.x

### ISSUE THREAD

**Issue by dexter93** [ChibiOS/ChibiOS-Contrib#307]
ChibiOS has released a stable 21.11.x branch. Is there a roadmap on a -Contrib version?

**Comment by fpoussin** [comment]
Hi,
I need to finish updating the repo for 21.6.x first, then I'll make the change directly to 21.11.x as it's the latest stable.

**Comment by tzarc** [comment]
Fair enough; Giovanni has mentioned that he's "cancelled" the 21.6 stream due to too many issues.

**Comment by tzarc** [comment]
Just an FYI from ChibiOS Discord:
![image](https://user-images.githubusercontent.com/2985843/145279049-f35e2dbb-2837-4c32-a3f7-795d8be1960a.png)

**Comment by zykrah** [comment]
@fpoussin Hi, are you still working on this? If not, do you have a list of what needs to be done for 21.11.x to be completed?

**Comment by zykrah** [comment]
Also, i noticed that a lot of the changes regarding rp2040 were merged from @hanya. Though upon analysing the current state of the 21.6.x fork, a lot of the dependencies for the RP2040 are missing, as the rest of the MCUs in /testhal are still using ChibOS stable 20.3.x (as from the build.yml). hanya's fork looks like it uses the master branch (which i assume is 21.11.x) of chibios though?

EDIT: I'd like to add that i have made a fork of contrib 21.6.x that builds successfully with rp2040 by making rp2040 build with the master branch of chibios and the others building with the older 20.3.x branch. Though, this is definitely more of a roundabout method of getting it to build, and doesnt actually update any of the older MCUs to the newer chibios version. 
https://github.com/zykrahgaming/ChibiOS-Contrib

**Comment by zykrah** [comment]
Out of impatience, I have now actually just made a PR which has (supposedly) updated ChibiOS-Contrib to the ChibiOS master branch (21.11.x): https://github.com/ChibiOS/ChibiOS-Contrib/pull/310
