### ISSUE TITLE
Lack elements in struct GPTConfig in the source of HT32's hal_gpt_lld.h

### ISSUE THREAD

**Issue by d93921012** [ChibiOS/ChibiOS-Contrib#368]
When I build my qmk project，I encountered the problem as follows.

Compiling: platforms/chibios/wait.c                                                                
platforms/chibios/wait.c: In function 'wait_us':
platforms/chibios/wait.c:24:54: error: excess elements in struct initializer [-Werror]
   24 |     static const GPTConfig gpt_cfg = {1000000, NULL, 0, 0}; /* 1MHz timer, no callback */
      |                                                      ^
platforms/chibios/wait.c:24:54: note: (near initialization for 'gpt_cfg')
platforms/chibios/wait.c:24:57: error: excess elements in struct initializer [-Werror]
   24 |     static const GPTConfig gpt_cfg = {1000000, NULL, 0, 0}; /* 1MHz timer, no callback */
      |                                                         ^
platforms/chibios/wait.c:24:57: note: (near initialization for 'gpt_cfg')
cc1: all warnings being treated as errors
 [ERRORS]
--------------------------

Comparing the source hal_gpt_lld.h of HT32 with the one of STM32，the two elements cr2 and dier should be added to the struct GPTConfig.

The source hal_gpt_lld.h of HT32 is in the folder -- "chibios-contrib\os\hal\ports\HT32\LLD\TIMv1\".

**Comment by dexter93** [comment]
the two elements are specific to STM32, can't comment on their validity on HT32.

But for your specific issue, that is a QMK nuisance. See how I tackled it on another chip [here](https://github.com/qmk/qmk_firmware/pull/21115)

```diff
-    static const GPTConfig gpt_cfg = {1000000, NULL, 0, 0}; /* 1MHz timer, no callback */
+    static const GPTConfig gpt_cfg = { .frequency = 1000000 }; /* 1MHz timer, no callback */
```

**Comment by d93921012** [comment]
Thank you.

**Comment by d93921012** [comment]
Thank you.
